name: flutter_admin_dashboard
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"


dependencies:
  animated_custom_dropdown: ^2.0.0
  cloud_firestore: ^4.13.3
  cupertino_icons: ^1.0.6
  dio: ^5.3.4
  dropdown_search: ^5.0.6
  email_validator: ^2.1.17
  fan_carousel_image_slider: ^0.1.2
  fan_floating_menu: ^0.0.1
  firebase_core: ^2.24.0
  firebase_storage: ^11.5.3
  fluro: ^2.0.5
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.9.0
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  get: ^4.6.6
  google_fonts: ^6.1.0
  hive: ^2.2.3
  image_picker: ^1.0.4
  lottie: ^2.7.0
  pluto_grid: ^7.0.2
  provider: ^6.1.1
  remove_background: ^0.0.1
  shared_preferences: ^2.2.2
  slide_countdown: ^1.3.2
  syncfusion_flutter_datepicker: ^22.2.12


dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

